services:
  fishtest-worker:
    restart: no
    build:
      dockerfile: ./Dockerfile
      args:
        - NUM_WORKERS=$NUM_WORKERS
        - WORKER_ARGS=$WORKER_ARGS

    container_name: fishtest-worker
    image: fishtest-worker
