services:
  fishtest-worker:
    restart: no
    build:
      dockerfile: ./Dockerfile
    container_name: fishtest-worker
    image: fishtest-worker
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - NUM_WORKERS
      - WORKER_ARGS
